// if (typeof jQuery == 'undefined'){
//   console.log('oops! I still have to link my jQuery properly!');
// } else {console.log('I did it! I linked jQuery and this js file!')};

//jQuery setup
$(() => {
// const $body = $('body');
// console.log($body);
const $container = $('#container');
console.log($container);
const $h1 = $('<h1>').text('Year One');
const $h2 = $('<h2>').text('Brendan');
const $h3 = $('<h3>').text('Ravenclaw');
const $h4Pet = $('<h4>').text('Meech').addClass('cat');
const $h4Wand = $('<h4>').text('Maple wood with a Unicorn hair core 10 ¾" and Quite Bendy flexibility');
const $trunk = $('<ul>');
console.log($trunk);
const $butter = $('<li>').text('butter beer');
const $cloak = $('<li>').text('invisiblity cloak').addClass('secret');
const $map = $('<li>').text('magic map').addClass('secret');
const $time = $('<li>').text('time turner').addClass('secret');
const $leash = $('<li>').text('leash').addClass('cat');
const $beans = $('<li>').text('Bertie Bott\'s Every Flavor Beans');
const $tableHead = $('<h5>').text('Spring 2017');
const $table = $('<table>');
const $thread1 = $('<tr>');
const $innerThread1 = $('<th>').text('Day');
const $innerThread2 = $('<th>').text('Class');
const $thread2 = $('<tr>');
const $tdMon = $('<td>').text('Monday');
const $tdMonClass = $('<td>').text('Defence Against The Dark Arts, Quidditch, Charms, Potions');
const $thread3 = $('<tr>');
const $thread4 = $('<tr>');
const $thread5 = $('<tr>');
const $thread6 = $('<tr>');
const $tdTues = $('<td>').text('Tuesday');
const $tdWed = $('<td>').text('Wednesday');
const $tdThurs = $('<td>').text('Thursday');
const $tdFri = $('<td>').text('Friday');
const $tdTuesClass = $('<td>').text('Wands');
const $tdWedClass = $('<td>').text('Alchemy');
const $tdThursClass = $('<td>').text('Transfiguration');
const $tdFriClass = $('<td>').text('History of Magic');
const $chest = $('<ul>');


$container.append($h1);
$container.append($h2);
$container.append($h3);
$container.append($h4Pet);
$container.append($h4Wand);
$container.append($trunk);
$trunk.append($butter);
$trunk.append($cloak);
$trunk.append($map);
$trunk.append($time);
$trunk.append($leash);
$trunk.append($beans);
$container.append($tableHead);
$container.append($table);
$table.append($thread1);
$table.append($thread2);
$table.append($thread3);
$table.append($thread4);
$table.append($thread5);
$table.append($thread6);
$thread1.append($innerThread1);
$thread1.append($innerThread2);
$thread2.append($tdMon);
$thread2.append($tdMonClass);
$thread3.append($tdTues);
$thread3.append($tdTuesClass);
$thread4.append($tdWed);
$thread4.append($tdWedClass);
$thread5.append($tdThurs);
$thread5.append($tdThursClass);
$thread6.append($tdFri);
$thread6.append($tdFriClass);
$h4Wand.remove();
$butter.remove();
$h4Wand.text('The Elder Wand');
$h4Pet.after($h4Wand);
$h4Wand.css('color', 'red');
$h4Pet.remove();
$tdTuesClass.after($h4Pet);
$h4Pet.remove();
$h4Wand.before($h4Pet);
$('.secret').hide('slow').delay(2000);
$('.secret').show('slow');
$h4Pet.addClass('cabbage');
$tableHead.text('Fall 2018');
$trunk.prepend($butter);
$trunk.replaceWith($chest);
$chest.append($butter);
$chest.append($cloak);
$chest.append($map);
$chest.append($time);
$chest.append($leash);
$chest.append($beans);


})
